# Generated by Django 4.1.2 on 2022-11-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('developer', models.ForeignKey(db_column='developer', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.developer')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('game', models.ForeignKey(db_column='gameid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='ExTime.games')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'servicetype',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('is_seller', models.IntegerField(db_column='is-seller')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Servicescreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=500)),
                ('serviceid', models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service')),
            ],
            options={
                'db_table': 'servicescreenshot',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.servicetype'),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.users'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('review_text', models.TextField(db_column='review text', max_length=1000)),
                ('rating', models.IntegerField()),
                ('serviceid', models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service')),
                ('user_id', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.users')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service')),
            ],
            options={
                'db_table': 'orderlist',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.users'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.users')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
