# Generated by Django 4.1.2 on 2022-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
