# Generated by Django 4.1.2 on 2022-11-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0002_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
