# Generated by Django 4.1.2 on 2022-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0003_rename_developer_games_developer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='typename',
            field=models.CharField(max_length=50),
        ),
    ]
