# Generated by Django 4.1.2 on 2022-11-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0003_orderlist_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='icon',
        ),
    ]
