# Generated by Django 4.1.2 on 2022-10-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0005_alter_user_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='developer_id',
            new_name='developer',
        ),
        migrations.AlterField(
            model_name='service',
            name='gameid',
            field=models.ForeignKey(db_column='gameid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='ExTime.games'),
        ),
    ]
